# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: coskuntekin › front-end developer
email: mail@coskuntekin.com
description: I write stuff about front-end development and about HTML5, CSS3, DOM, jQuery, AngularJS, Middleman, Ruby on Rails
baseurl: ""
url: "http://coskuntekin.com"
twitter_username: coskuntekin
github_username:  coskuntekin

# Build settings
markdown: kramdown
